name: Feature Request
labels: ["enhancement"]
description: Suggest an idea to container-auto-tune
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this!
  - type: textarea
    id: feat-description
    attributes:
      label: Describe This Feature
      description: A clear and concise description of what the Feature is. 
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: assign
    attributes:
      label: Assgin People
      description: If possible, please assign the people to fix this issue.
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Maybe you have considered some ideas or solutions about this feature.
    validations:
      required: true
  - type: textarea
    id: ac
    attributes:
      label: Acceptance criteria (AC)
      description: If possible, please give the ac for feature when it was finished.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
